In [1]:
import sys
import pandas as pd
from datetime import date
sys.path.append("..")

In [2]:
from utils.market_data import prepare_df
from utils.mean_reversion_backtest import optimize, run_backtest, walk_forward_optimization
from utils.get_tickers import get_all_futures

C:\Users\bakae\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
tickers_df = get_all_futures()

In [7]:
tickers_df.head()

,secid,name,start_date,expiration_date,asset_code,underlying_asset,is_traded,underlying_type
0,CNYRUBF,CNYRUBF,2022-04-23,2100-01-01,CNYRUBTOM,CNYRUB_TOM,1,currency_selt
1,EURRUBF,EURRUBF,2022-04-23,2100-01-01,EURRUBTOM,EUR_RUB__TOM,1,currency_selt
2,GAZPF,GAZPF,2024-10-01,2100-01-01,GAZPF,GAZP,1,stock_shares
3,GLDRUBF,GLDRUBF,2023-07-11,2100-01-01,GLDRUBTOM,GLDRUB_TOM,1,currency_metal
4,IMOEXF,IMOEXF,2023-11-14,2100-01-01,IMOEX,IMOEX,1,stock_index

In [10]:
futures_tickers = tickers_df.loc[tickers_df['underlying_type'] == "stock_shares"]
futures_tickers

,secid,name,start_date,expiration_date,asset_code,underlying_asset,is_traded,underlying_type
2,GAZPF,GAZPF,2024-10-01,2100-01-01,GAZPF,GAZP,1,stock_shares
6,SBERF,SBERF,2024-10-01,2100-01-01,SBERF,SBER,1,stock_shares
40,GZM7,GAZR-6.27,2026-06-03,2027-06-18,GAZR,GAZP,1,stock_shares
41,GZH7,GAZR-3.27,2026-03-05,2027-03-19,GAZR,GAZP,1,stock_shares
42,GZZ6,GAZR-12.26,2025-12-04,2026-12-18,GAZR,GAZP,1,stock_shares
...,...,...,...,...,...,...,...,...
466,PIU6,PIKK-9.26,2026-03-05,2026-09-18,PIKK,PIKK,1,stock_shares
467,PIM6,PIKK-6.26,2025-12-04,2026-06-19,PIKK,PIKK,1,stock_shares
470,RNU6,ROSN-9.26,2025-09-19,2026-09-18,ROSN,ROSN,1,stock_shares
471,RNM6,ROSN-6.26,2023-03-07,2026-06-19,ROSN,ROSN,1,stock_shares
523,CHM6,CHMF-6.26,2025-12-04,2026-06-19,CHMF,CHMF,1,stock_shares

In [18]:
from datetime import datetime

start_date = date(2000, 1, 1)
end_date = datetime.now()
for row in futures_tickers.itertuples():
    inst1={
    'ticker': row.underlying_asset,
    'engine':"stock",
    'board':"TQBR",
    'market':"shares"
    }
    inst2={
        'ticker':row.secid,
        'engine':"futures",
        'board':"RFUD",
        'market':"forts"
    }

    df = prepare_df(inst1, inst2, start_date, end_date, interval=10)
    print(df)
    break

                 timestamp  open_x  close_x  high_x   low_x      value_x  \
0      2014-06-09 10:00:00  144.02   144.16  144.78  144.00  115259065.9
1      2014-06-09 10:10:00  144.18   143.62  144.20  143.60   92635541.5
2      2014-06-09 10:20:00  143.62   143.64  143.74  143.50   78514596.6
3      2014-06-09 10:30:00  143.64   143.68  143.81  143.54   86464723.9
4      2014-06-09 10:40:00  143.68   143.29  143.72  143.03  116152165.2
...                    ...     ...      ...     ...     ...          ...
214489 2026-06-04 17:00:00  115.80   115.92  116.10  115.75   86131592.7
214490 2026-06-04 17:10:00  115.90   115.90  116.05  115.89   19415075.5
214491 2026-06-04 17:20:00  115.91   116.07  116.11  115.86   44379181.8
214492 2026-06-04 17:30:00  116.03   116.04  116.08  115.91   16751350.8
214493 2026-06-04 17:40:00  116.02   115.99  116.04  115.96    5631417.4

        volume_x                end_x  open_y  close_y  high_y   low_y  \
0         798230  2014-06-09 10:09:59     NaN      NaN     NaN     NaN
1         643790  2014-06-09 10:19:59     NaN      NaN     NaN     NaN
2         546760  2014-06-09 10:29:59     NaN      NaN     NaN     NaN
3         601940  2014-06-09 10:39:59     NaN      NaN     NaN     NaN
4         810310  2014-06-09 10:49:59     NaN      NaN     NaN     NaN
...          ...                  ...     ...      ...     ...     ...
214489    742850  2026-06-04 17:09:59  115.98   116.10  116.27  115.96
214490    167440  2026-06-04 17:19:59  116.10   116.14  116.20  116.10
214491    382650  2026-06-04 17:29:59  116.10   116.20  116.25  116.08
214492    144400  2026-06-04 17:39:59  116.20   116.20  116.21  116.06
214493     48550  2026-06-04 17:46:16  116.16   116.09  116.17  116.09

        value_y  volume_y                end_y
0           NaN       NaN                  NaN
1           NaN       NaN                  NaN
2           NaN       NaN                  NaN
3           NaN       NaN                  NaN
4           NaN       NaN                  NaN
...         ...       ...                  ...
214489      0.0     499.0  2026-06-04 17:09:59
214490      0.0      69.0  2026-06-04 17:19:59
214491      0.0     883.0  2026-06-04 17:29:59
214492      0.0     521.0  2026-06-04 17:39:59
214493      0.0     237.0  2026-06-04 17:46:22

[214494 rows x 15 columns]